name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gptchat:$(date +%s)
    - name: Save Docker image
      run: |
        image_id=$(docker images -q gptchat)
        docker save $image_id -o image.tar
    
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Publish Docker image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./image.tar"
        target: "/home/${{ secrets.USERNAME }}/image.tar"
